### ISSUE TITLE
Not Showing up?

### ISSUE THREAD

**Issue by Airfisher142** [LeeOkeefe/slayer-assistant-plugin#18]
![image](https://user-images.githubusercontent.com/92659067/167301109-6c7d87cd-90d2-4e39-b2c3-1a44056732cd.png)
No side bar icon atall... I hope I can use this soon, its very hepful

**Comment by pettrs** [comment]
Having the same issue. does not show up on the side as as shown in the instructions

**Comment by LeeOkeefe** [comment]
Thanks for raising this, I'm looking into it.

I have found that the problem is occurring on the production client of RuneLite only, but not when I run a local copy of it.

**Comment by zahti** [comment]
I don't even see the Slayer Assistant plugin in my list after installing and searching.

**Comment by LeeOkeefe** [comment]
Thanks @zahti, an update (1.0.2) has been pushed out this morning, it should now be installing and showing the icon correctly.

Unfortunately, there is still an issue loading task information. I believe it's due to an image name having an uppercase, I'm not sure how it ever worked when I ran it locally! The fix will hopefully get pushed out soon.

**Comment by Airfisher142** [comment]
![image](https://user-images.githubusercontent.com/92659067/168241745-75be55c1-d707-44e9-a092-a36375a66471.png)
 
Not to rush anything just updating, v1.0.2, I'm able to view the plugin on the sidebar and search for a slayer task, but once chosen, it doesn't give any information nor any buttons to exit/choose another one :)

**Comment by LeeOkeefe** [comment]
Thanks @Airfisher142, v1.0.3 has now been pushed out to solve that issue.

**Comment by Airfisher142** [comment]
![image](https://user-images.githubusercontent.com/92659067/168257909-602f8700-e1a7-4a58-bf59-da978ec00732.png)
Perfect, thank you :) It is honestly an amazing and helpful plugin to have @LeeOkeefe :)
