### ISSUE TITLE
Link to Wiki for Task

### ISSUE THREAD

**Issue by hawkins** [LeeOkeefe/slayer-assistant-plugin#27]
Would love to have a link to the wiki page for a chosen task. For instance, Vampyres would link to https://oldschool.runescape.wiki/w/Slayer_task/Vampyres. Would help get even more information when needed. Happy to PR if desired, too!

**Comment by LeeOkeefe** [comment]
That sounds like a useful feature to have if you would like to implement it. 

The only question I have is about how you imagine the wiki link being presented?

**Comment by Juzzed** [comment]
This would be a nice feature.  
There was actually a plugin dedicated to doing only that, but seems to be abandoned now (https://github.com/ffalor/slayer-wiki). 
An idea would be to add a tab with a wiki icon and in there a clickable link to the wiki. Optionaly it could be implemented as an option in the menu of the slayer gear like in the plugin slayer-wiki before. 
Maybe I will have the time on the weekend for implementing this and making a pull request.
