### ISSUE TITLE
Blank Creature Bug

### ISSUE THREAD

**Issue by Toxers** [LeeOkeefe/slayer-assistant-plugin#31]
Whenever I click on some creature, the tab goes blank, it doesn't show anything, and there is no buttons to go back.

List of Creatures whos bugged:
- Rune Dragon
- Earth Warrior
- Harpire Bug Swarm
- Sea Snake

I have to re-enable the program to get it back to working state again.

**Comment by LeeOkeefe** [comment]
Thanks for raising this, I have submitted a PR which will hopefully be reviewed by the RuneLite team soon. 

I will close this issue once it's been approved and confirm that it's resolved.

_To see details, see PR https://github.com/LeeOkeefe/slayer-assistant-plugin/pull/32_
